- name: install the nginx server
  ansible.builtin.package:
    name: nginx
    state: present

- name: enable the nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: common tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: copy the expense file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart nginx

# - name: enable the nginx service
#   ansible.builtin.service:
#     name: nginx
#     state: restarted 